// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/kyc/pan/{accountId}/verify": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks the named account's KYC row as PAN-verified. Required before that account can request credit analytics. The caller must be an admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Verify an account's PAN (admin only)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Account id whose PAN is being verified",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.KYCRecord"
                        }
                    },
                    "400": {
                        "description": "accountId must be an integer",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "403": {
                        "description": "Not an admin",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "No PAN on file for this account",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/google": {
            "post": {
                "description": "Verifies a Google ID token (issued by the Android/iOS Google Sign-In SDK) and returns a session JWT. On first login, creates a verified account; on subsequent logins, reuses the existing account. If the Google email matches an existing account, the Google identity is linked onto it. Requires the Web OAuth client ID to be configured (AUTH_GOOGLE_CLIENT_ID); otherwise returns 503.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with Google",
                "parameters": [
                    {
                        "description": "Google ID token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.googleLoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.AuthResult"
                        }
                    },
                    "400": {
                        "description": "Validation failed (missing idToken)",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Invalid Google token",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Google identity already linked to another account",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "503": {
                        "description": "Google login is not configured",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Verifies email + password and returns a session JWT. Requires the email to be verified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with email + password",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.AuthResult"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Invalid email or password / email not verified",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/otp/resend": {
            "post": {
                "description": "Re-issues the signup OTP for an unverified email, subject to cooldown / send limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Resend signup verification OTP",
                "parameters": [
                    {
                        "description": "Email to resend to",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.resendReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"message\\\": \\\"Verification code re-sent\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Validation failed / cooldown / send limit",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "No signup found for this email",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Email is already verified",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Creates a PENDING account with an unverified password identity and emails a verification OTP. Re-signing up for an unverified email updates the password and re-issues the OTP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up with email + password",
                "parameters": [
                    {
                        "description": "Signup credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.signupReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.SignupResult"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "post": {
                "description": "Checks the signup OTP; on success verifies the identity, activates the account, and returns a session JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify email with OTP",
                "parameters": [
                    {
                        "description": "Email + OTP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.verifyEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.AuthResult"
                        }
                    },
                    "400": {
                        "description": "Wrong / expired / locked OTP",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/credit-analytics/reports": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a paginated list of the caller's reports, newest first. Each item carries only the report id (unique identifier) and generation date.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credit-analytics"
                ],
                "summary": "List the authenticated account's credit-analytics reports",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "1-indexed page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "page size (default 20, max 100)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.ReportPage"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/credit-analytics/reports/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the full report row (including the persisted upstream response body) for one of the caller's own reports.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credit-analytics"
                ],
                "summary": "Fetch a credit-analytics report by id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Report id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.CreditAnalyticsRequest"
                        }
                    },
                    "400": {
                        "description": "id must be an integer",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Report not found (or belongs to another account)",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/credit-analytics/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Builds the Digitap /credit_analytics/request payload from the authenticated account's profile and KYC record (mobile, name, PAN), plus server-generated values (client_ref_num, otp, timestamp), then persists the request and full upstream response and returns the stored row. Only device_ip is taken from the request body; if omitted it falls back to the detected remote IP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credit-analytics"
                ],
                "summary": "Request a credit analysis from Digitap",
                "parameters": [
                    {
                        "description": "Credit-analytics request (device_ip optional; defaults to the caller's IP)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.CreditAnalyticsInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.CreditAnalyticsRequest"
                        }
                    },
                    "400": {
                        "description": "Invalid request body / missing profile or PAN / upstream 400",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated / upstream 401",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "Upstream tradeline limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/kyc/pan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accepts a PAN (Permanent Account Number), validates the format, and upserts it against the account's KYC record. A re-submission overwrites any existing PAN and resets verification to PENDING.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Submit the authenticated account's PAN",
                "parameters": [
                    {
                        "description": "PAN to store",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.submitPanReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.KYCRecord"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body / PAN format",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "PAN already linked to another account",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns every order placed by the authenticated account, newest first.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "List the authenticated account's orders",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/credit-report-service_internal_models.Order"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates an order for the given product against the authenticated account and registers it with Cashfree. The response carries ` + "`" + `paymentSessionId` + "`" + ` and ` + "`" + `mode` + "`" + `, which the frontend passes to the Cashfree JS SDK to open checkout.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Create an order and start checkout",
                "parameters": [
                    {
                        "description": "Product to purchase",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createOrderReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.PurchaseResult"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body / productCode missing or unknown",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Product is not available for purchase",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "502": {
                        "description": "Payment gateway could not create the order",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/orders/{orderId}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single order owned by the authenticated account. If the order is still awaiting payment its status is reconciled against Cashfree before being returned, so this is the endpoint to poll after checkout closes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "Get one order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order id returned from order creation",
                        "name": "orderId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.Order"
                        }
                    },
                    "400": {
                        "description": "orderId is not valid",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Order not found",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/payments/cashfree/webhook": {
            "post": {
                "description": "Server-to-server endpoint called by Cashfree on payment success/failure. Not for client use: there is no bearer auth, trust comes from the ` + "`" + `x-webhook-signature` + "`" + ` HMAC over the raw body, and ` + "`" + `x-idempotency-key` + "`" + ` de-duplicates redeliveries.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Cashfree payment webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cashfree signature timestamp",
                        "name": "x-webhook-timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Base64 HMAC-SHA256 of timestamp+body",
                        "name": "x-webhook-signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cashfree delivery id, used to drop duplicates",
                        "name": "x-idempotency-key",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid webhook payload",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Invalid webhook signature",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Reports whether the service is up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "UP",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the active product catalog with prices. Use a product's ` + "`" + `code` + "`" + ` as the ` + "`" + `productCode` + "`" + ` when creating an order.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orders"
                ],
                "summary": "List purchasable products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/credit-report-service_internal_models.Product"
                            }
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the full account record for the current session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get the authenticated account's profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.Account"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sets first/last name (required) and optional date of birth (YYYY-MM-DD), marking the profile step complete.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update the authenticated account's profile",
                "parameters": [
                    {
                        "description": "Profile fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.Account"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "credit-report-service_internal_apperr.ErrorBody": {
            "type": "object",
            "properties": {
                "details": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_models.Account": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profileCompleted": {
                    "type": "boolean"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_models.CreditAnalyticsRequest": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "integer"
                },
                "clientRefNum": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "httpStatus": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "mobileNo": {
                    "type": "string"
                },
                "requestBody": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "requestId": {
                    "type": "string"
                },
                "responseBody": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "resultCode": {
                    "type": "integer"
                }
            }
        },
        "credit-report-service_internal_models.KYCRecord": {
            "type": "object",
            "properties": {
                "aadhaarLast4": {
                    "type": "string"
                },
                "aadhaarPanLinked": {
                    "type": "boolean"
                },
                "aadhaarReference": {
                    "type": "string"
                },
                "accountId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pan": {
                    "type": "string"
                },
                "panName": {
                    "type": "string"
                },
                "panVerified": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "verifiedAt": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_models.Order": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "cfOrderId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "failureReason": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "paidAt": {
                    "type": "string"
                },
                "paymentMethod": {
                    "type": "string"
                },
                "paymentSessionId": {
                    "type": "string"
                },
                "productCode": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_models.Product": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "amount": {
                    "type": "number"
                },
                "code": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.AuthResult": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/credit-report-service_internal_models.Account"
                },
                "expiresAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.CreditAnalyticsInput": {
            "type": "object",
            "properties": {
                "device_ip": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.PurchaseResult": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "cfOrderId": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "mode": {
                    "type": "string"
                },
                "orderId": {
                    "type": "string"
                },
                "paymentSessionId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.ReportPage": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/credit-report-service_internal_service.ReportSummary"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "credit-report-service_internal_service.ReportSummary": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "credit-report-service_internal_service.SignupResult": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler.createOrderReq": {
            "type": "object",
            "properties": {
                "productCode": {
                    "type": "string",
                    "example": "CREDIT_ANALYSIS"
                }
            }
        },
        "internal_handler.googleLoginReq": {
            "type": "object",
            "properties": {
                "idToken": {
                    "type": "string",
                    "example": "eyJhbGciOiJSUzI1NiIs..."
                }
            }
        },
        "internal_handler.loginReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "hunter2pass"
                }
            }
        },
        "internal_handler.resendReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "internal_handler.signupReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "hunter2pass"
                }
            }
        },
        "internal_handler.submitPanReq": {
            "type": "object",
            "properties": {
                "pan": {
                    "type": "string",
                    "example": "ABCDE1234F"
                }
            }
        },
        "internal_handler.updateProfileReq": {
            "type": "object",
            "properties": {
                "dateOfBirth": {
                    "type": "string",
                    "example": "1815-12-10"
                },
                "firstName": {
                    "type": "string",
                    "example": "Ada"
                },
                "lastName": {
                    "type": "string",
                    "example": "Lovelace"
                }
            }
        },
        "internal_handler.verifyEmailReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003cjwt\u003e\" — obtain via POST /api/auth/login or /api/auth/verify-email",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Credit Report Service API",
	Description:      "REST API for the credit-report Android app: email/password auth with OTP verification, JWT sessions, profile management, and credit-report CRUD.\n\nAll routes are mounted under `/api`. Protected routes require an `Authorization: Bearer <jwt>` header obtained from login or email verification.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
