// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Verifies email + password and returns a session JWT. Requires the email to be verified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in with email + password",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.loginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.AuthResult"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Invalid email or password / email not verified",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/otp/resend": {
            "post": {
                "description": "Re-issues the signup OTP for an unverified email, subject to cooldown / send limits.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Resend signup verification OTP",
                "parameters": [
                    {
                        "description": "Email to resend to",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.resendReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\\\"message\\\": \\\"Verification code re-sent\\\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Validation failed / cooldown / send limit",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "No signup found for this email",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Email is already verified",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Creates a PENDING account with an unverified password identity and emails a verification OTP. Re-signing up for an unverified email updates the password and re-issues the OTP.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up with email + password",
                "parameters": [
                    {
                        "description": "Signup credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.signupReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.SignupResult"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/auth/verify-email": {
            "post": {
                "description": "Checks the signup OTP; on success verifies the identity, activates the account, and returns a session JWT.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify email with OTP",
                "parameters": [
                    {
                        "description": "Email + OTP",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.verifyEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.AuthResult"
                        }
                    },
                    "400": {
                        "description": "Wrong / expired / locked OTP",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "Email already registered",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/credit-analytics/request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Proxies the request body to the Digitap /credit_analytics/request API (spec V2.7 §1.4.1), persists the request and full upstream response against the authenticated account, and returns the stored row.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credit-analytics"
                ],
                "summary": "Request a credit analysis from Digitap",
                "parameters": [
                    {
                        "description": "Credit-analytics request payload (Digitap §1.4.1)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_service.CreditAnalyticsInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.CreditAnalyticsRequest"
                        }
                    },
                    "400": {
                        "description": "Invalid request body / validation failure / upstream 400",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated / upstream 401",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "422": {
                        "description": "Upstream tradeline limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/kyc/pan": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Accepts a PAN (Permanent Account Number), validates the format, and upserts it against the account's KYC record. A re-submission overwrites any existing PAN and resets verification to PENDING.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kyc"
                ],
                "summary": "Submit the authenticated account's PAN",
                "parameters": [
                    {
                        "description": "PAN to store",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.submitPanReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.KYCRecord"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body / PAN format",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "409": {
                        "description": "PAN already linked to another account",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Reports whether the service is up.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "UP",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the full account record for the current session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Get the authenticated account's profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.Account"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sets first/last name (required) and optional date of birth (YYYY-MM-DD), marking the profile step complete.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Update the authenticated account's profile",
                "parameters": [
                    {
                        "description": "Profile fields",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.updateProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_models.Account"
                        }
                    },
                    "400": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "401": {
                        "description": "Not authenticated",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    },
                    "404": {
                        "description": "Account not found",
                        "schema": {
                            "$ref": "#/definitions/credit-report-service_internal_apperr.ErrorBody"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "credit-report-service_internal_apperr.ErrorBody": {
            "type": "object",
            "properties": {
                "details": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_models.Account": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastName": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "profileCompleted": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_models.CreditAnalyticsRequest": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "integer"
                },
                "clientRefNum": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "httpStatus": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "mobileNo": {
                    "type": "string"
                },
                "requestBody": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "requestId": {
                    "type": "string"
                },
                "responseBody": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "resultCode": {
                    "type": "integer"
                }
            }
        },
        "credit-report-service_internal_models.KYCRecord": {
            "type": "object",
            "properties": {
                "aadhaarLast4": {
                    "type": "string"
                },
                "aadhaarPanLinked": {
                    "type": "boolean"
                },
                "aadhaarReference": {
                    "type": "string"
                },
                "accountId": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "pan": {
                    "type": "string"
                },
                "panName": {
                    "type": "string"
                },
                "panVerified": {
                    "type": "boolean"
                },
                "provider": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "verifiedAt": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.AuthResult": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/credit-report-service_internal_models.Account"
                },
                "expiresAt": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.CreditAnalyticsInput": {
            "type": "object",
            "properties": {
                "client_ref_num": {
                    "type": "string"
                },
                "consent_acceptance": {
                    "type": "string"
                },
                "consent_message": {
                    "type": "string"
                },
                "date_of_birth": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "device_ip": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile_no": {
                    "type": "string"
                },
                "name_lookup": {
                    "type": "integer"
                },
                "otp": {
                    "type": "string"
                },
                "pan": {
                    "type": "string"
                },
                "report_type": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "credit-report-service_internal_service.SignupResult": {
            "type": "object",
            "properties": {
                "accountId": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler.loginReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "hunter2pass"
                }
            }
        },
        "internal_handler.resendReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "internal_handler.signupReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "hunter2pass"
                }
            }
        },
        "internal_handler.submitPanReq": {
            "type": "object",
            "properties": {
                "pan": {
                    "type": "string",
                    "example": "ABCDE1234F"
                }
            }
        },
        "internal_handler.updateProfileReq": {
            "type": "object",
            "properties": {
                "dateOfBirth": {
                    "type": "string",
                    "example": "1815-12-10"
                },
                "firstName": {
                    "type": "string",
                    "example": "Ada"
                },
                "lastName": {
                    "type": "string",
                    "example": "Lovelace"
                }
            }
        },
        "internal_handler.verifyEmailReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "otp": {
                    "type": "string",
                    "example": "123456"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "\"Bearer \u003cjwt\u003e\" — obtain via POST /api/auth/login or /api/auth/verify-email",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Credit Report Service API",
	Description:      "REST API for the credit-report Android app: email/password auth with OTP verification, JWT sessions, profile management, and credit-report CRUD.\n\nAll routes are mounted under `/api`. Protected routes require an `Authorization: Bearer <jwt>` header obtained from login or email verification.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
